source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook 'yum'
  cookbook 'windows'
  cookbook 'homebrew'
  # commented out the following two lines as they caused issues when Berkshelf was run
  # cookbook 'test_java', path: 'test/fixtures/cookbooks/test_java'
  # cookbook 'freebsd_bash', path: 'test/fixtures/cookbooks/freebsd_bash'
end
