name             'chefnexus'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chefnexus'
long_description 'Installs/Configures chefnexus'
version          '0.1.0'
